cookietemple_version: '1.2.4 # <<COOKIETEMPLE_NO_BUMP>>'
domain: web
language: python
project_slug: mlf_core_website
project_slug_no_hyphen: mlf_core_website
template_version: '1.1.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: web-website-python
github_username: mlf-core
creator_github_username: zethson
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: mlf-core
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: mlf_core_website
project_short_description: The mlf-core website.
version: 0.1.0
license: MIT
webtype: website
command_line_interface: Click
testing_library: pytest
web_framework: flask
setup_type: basic
use_frontend: false
url: mlf-core.com
vmusername: cookietempleuser
